apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: soulcaster
  namespace: soulcaster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: soulcaster
    spec:
      containers:
      - name: soulcaster
        image: gomagames/soulcaster:1.0.0
        ports:
        - containerPort: 80
